# Label for documentation-related changes
"documentation":
  - changed-files:
    - any-glob-to-any-file:
      - docs/**
      - '*.md'

# Label for public assets and styling
"assets":
  - changed-files:
    - any-glob-to-any-file:
      - public/assets/**

"popup":
  - changed-files:
    - any-glob-to-any-file:
      - public/src/popup/**
      - src/popup/**

"options-page":
  - changed-files:
    - any-glob-to-any-file:
      - public/src/options/**
      - src/options/**

"background":
  - changed-files:
    - any-glob-to-any-file:
      - src/background/**

"content script":
  - changed-files:
    - any-glob-to-any-file:
      - src/contentScript/**

"core":
  - changed-files:
    - any-glob-to-any-file:
      - src/docFillerCore/**

"consensus-engine":
  - changed-files:
    - any-glob-to-any-file:
      - src/docFillerCore/engines/consensusEngine.ts

"extractor-engine":
  - changed-files:
    - any-glob-to-any-file:
      - src/docFillerCore/engines/fieldExtractorEngine.ts

"filler-engine":
  - changed-files:
    - any-glob-to-any-file:
      - src/docFillerCore/engines/fillerEngine.ts

"gpt-engine":
  - changed-files:
    - any-glob-to-any-file:
      - src/docFillerCore/engines/gptEngine.ts

"prompt-engine":
  - changed-files:
    - any-glob-to-any-file:
      - src/docFillerCore/engines/promptEngine.ts

"parser-engine":
  - changed-files:
    - any-glob-to-any-file:
      - src/docFillerCore/engines/validatorEngine.ts

"utils":
  - changed-files:
    - any-glob-to-any-file:
      - src/utils/**

"manifest":
  - changed-files:
    - any-glob-to-any-file:
      - public/manifest.ts

# Label for TypeScript utilities and tools
"config":
  - changed-files:
    - any-glob-to-any-file:
      - eslint.config.js
      - tsconfig.json
      - .prettierrc
      - biome.json

# Label for licensing and governance
"governance":
  - changed-files:
    - any-glob-to-any-file:
      - LICENSE
      - docs/GOVERNANCE.md
      - docs/CODE_OF_CONDUCT.md

# Label for testing or metrics
"metrics":
  - changed-files:
    - any-glob-to-any-file:
      - src/options/metrics.ts
      - src/utils/metricsCalculator.ts

# Label for build and CI-related files
"build":
  - changed-files:
    - any-glob-to-any-file:
      - Makefile
      - tools/**

"ci":
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/**